### ISSUE TITLE
TypeError: dataPerSchema[id].push is not a function

### ISSUE THREAD

**Issue by KingCosmic** [geckosio/typed-array-buffer-schema#16]
**Describe the bug**
When I tried adding typed-array-buffer-schema to my geckos application everything works fine until a 3rd player joins then things error out with this 
![error](https://user-images.githubusercontent.com/24766991/152605519-ec041f85-29fd-4134-8d0a-84135d3cf0c2.png)

the code seems to do a undefined check on dataPerSchema[id] and if it's undefined set it to an array otherwise push to it. unsure if another type of data is getting put into it somehow or whatnot.

my model is
![here](https://user-images.githubusercontent.com/24766991/152605653-73d8be02-d22e-4dee-8797-dacc5674f896.png)

**Comment by IceHacks** [comment]
I am not completely sure, but I think there was an issue where you couldnt have multiple of the same schema. Try making two different schemas for `newEntities` and `updatedEntities.`

I'd like to see more of your code to get a better idea of what the problem is.

**Comment by KingCosmic** [comment]
there's a lot of moving parts here but I'll try and figure out what the most "important" might be

**Comment by Codezilluh** [comment]
Hey there!

I believe the problem is caused by this line of code in your main schema:
```js
removedEntities: [{ type: string8, length: 24}]
```

You must define a schema in order for this array data structure to work. Do what you did for `fullPlayerSchema`. It should end up like this:
```js
const removedEntSchema = BufferSchema.schema("remEnt", {
  name: { type: string8, length: 24 }
})
```

Also, @IceHacks is right. You cannot currently embed the same schema twice (#10).

This is all due to fixable limitations in parsing. I probably won't get around to fixing them though, as I am busy.

**Comment by KingCosmic** [comment]
gotcha, I haven't had the time to pull the rest of the code here but I'll give that a try and see if it works ty!

**Comment by KingCosmic** [comment]
that seems to have fixed it! ty for the help Edit: (making sure there as no duplicate schemas and Codez suggestion fixed it)
